### ISSUE TITLE
unable to access fields in temporary record

### ISSUE THREAD

**Issue by karel-un** [nikulukani/pyorient_native#5]
Already posted as pyorient issue, but it belongs probably here:

Using  pyorient_native 1.2.3 and pyorient 1.5.5 when result of query is not  actual record in database, but temporary record, fields in this record  can not be accesses by dotted syntax. For example:

res = client.query(SELECT *, @Rid, in('EQOSChild').@Rid AS parentrid ...

print(res[0].rid, res[0].parentrid)

when using native driver output is:

('OrientRecordLink', 42, 1) ('OrientRecordLink', 35, 0)

when using csv driver output is:

#42:1 #35:0

**Comment by karel-un** [comment]
mogui/pyorient#260

**Comment by nikulukani** [comment]
This is related to #2. This is fixed in the develop branch of pyorient (specifically the commits mogui/pyorient@10db8b754a9434e9a1519b8112f833153fd37cd0 through mogui/pyorient@6e68b280fac117c8be9b752b01ae638f5001afdd )and will be part of the next pyorient release. If you need it before then, please patch your pyorient installation with the above commits.

Closing for now, feel free to reopen if the above does not solve the issue.
